### ISSUE TITLE
Request for permission

### ISSUE THREAD

**Issue by IzzelAliz** [OtakuMegane/TallNether#1]
This is actually not a issue.
Dear developer, I love your awesome plugin TallNether so much, so could I have your permission to make a introduction thread on a chinese forum named MCBBS? (http://www.mcbbs.net)
I won't leak the jar and will redirect to your page. If you agree, I'd appreciate it a lot.
Sorry if I have troubled you.

**Comment by OtakuMegane** [comment]
I'm glad you like it so much. You can go ahead and make the thread on MCBBS, that's not a problem.
