### ISSUE TITLE
server crashed on startup.

### ISSUE THREAD

**Issue by andrewkm** [OtakuMegane/TallNether#12]
Caught this server crash on startup:

Console: https://pastebin.com/raw/aYYSF9CQ
Crash report: https://pastebin.com/raw/dpu0zEMt
TallNether config: https://pastebin.com/raw/CNYgekDF

Using Paper 1.16.5 Build 586
TallNether Build 2.5.5

**Comment by OtakuMegane** [comment]
Tried the config and a few variations but cannot reproduce the crash. Are there any other plugins or custom settings running that add or modify structures or generation (ores, etc)?

**Comment by andrewkm** [comment]
No, there are not, it seems to be rare and only on certain server startups.
Removing tallnether completely fixes the problem however.

**Comment by OtakuMegane** [comment]
Still haven't been able to get the crash through several dozen starts. TallNether is apparently triggering the problem or is a factor but I can't tell how. The exception being thrown is concurrent modification which means something else is interacting badly with the plugin's generator. If you try it with only TallNether does the crash still occur?

**Comment by andrewkm** [comment]
This was fixed in PaperMC.
