### ISSUE TITLE
1.16.2 is unsupported

### ISSUE THREAD

**Issue by calumari** [OtakuMegane/TallNether#3]
I apologize for being _that_ guy, but 1.16.2 bumped the nms revision and is unsupported.

Great plugin by the way! Thank you for maintaining it.

Edit: https://www.spigotmc.org/threads/tallnether.143809/page-7#post-3912945

**Comment by OtakuMegane** [comment]
Thanks. :) I pretty much assume something will break every update at this point since Mojang is working on the generator code a lot.

**Comment by calumari** [comment]
Closing as 1.16.2 support has been added. Great work, thanks!
