### ISSUE TITLE
Paper forks are breaking on 1.16.2

### ISSUE THREAD

**Issue by BillyGalbreath** [OtakuMegane/TallNether#4]
Your Paper detection is not done properly to detect forks of Paper (like [Tuinity](https://github.com/Spottedleaf/Tuinity), [Purpur](https://github.com/pl3xgaming/Purpur), [Yatopia](https://github.com/YatopiaMC/Yatopia), [Origami](https://github.com/Minebench/Origami), etc)

As you know, [CraftBukkit relocates fastutils](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/pom.xml#194-197) but [Paper does not relocate it](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0001-POM-Changes.patch#L169-L177), which is why it's important you have a [Paper specific nms helper](https://github.com/OtakuMegane/TallNether/blob/master/v1_16_R2/src/main/java/com/minefit/xerxestireiron/tallnether/v1_16_R2/TallNether_ChunkGeneratorAbstract_Paper.java#L19-L21) in your plugin to use the non-relocated fast utils. However, your plugin is checking [_very specifically_](https://github.com/OtakuMegane/TallNether/blob/master/v1_16_R2/src/main/java/com/minefit/xerxestireiron/tallnether/v1_16_R2/LoadHell.java#L28) for the server name to be "Paper" which fails on Paper forks, [like mine](https://github.com/pl3xgaming/Purpur/blob/ver/1.16.2/patches/server/0002-Rebrand.patch#L109).

Possible solution: It would be better check for the existence of `PaperConfig` in a try/catch to know if the environment is indeed a Paper environment. Or, you can use PaperLib to [handle this check for you](https://github.com/PaperMC/PaperLib/blob/master/src/main/java/io/papermc/lib/PaperLib.java#L35-L47) and you use [`PaperLib#isPaper()`](https://github.com/PaperMC/PaperLib/blob/master/src/main/java/io/papermc/lib/PaperLib.java#L255)

**Comment by OtakuMegane** [comment]
Appreciate the info, those are much better detection methods. It's been a long time since I put the detection in and it could use an update.
