### ISSUE TITLE
retrogenerate old chunks

### ISSUE THREAD

**Issue by 22s** [OtakuMegane/TallNether#5]
when going from pregenerated chunks to new chunks it cuts off, I know that this is intentional because its only supposed to affect new chunks but it would be cool for servers that have been using normal nether for months to be able to retrogenerate old chunks y120+ into new terrain even if its butchered its better than nothing. just an idea

![image](https://user-images.githubusercontent.com/58058658/92318191-88ba7580-efbd-11ea-8822-cc349d4dbe0c.png)

**Comment by OtakuMegane** [comment]
It's something I considered at one point but is pretty involved to implement. It's possible I will come back to the idea some day but for now I'm not adding new features, just doing maintenance.
